import {
  PrismaClient,
  type ColdChainStatus,
  type Grade,
  type Prisma,
  type ProduceCategory,
  type Region,
} from "@prisma/client";
import { hashPassword } from "../lib/auth";

/**
 * Development seed for KasetHub.
 *
 * Safe to re-run. Reference data (provinces, users, watches) is upserted on
 * stable natural keys; volatile marketplace rows (lots, bids, orders, chat,
 * market prices) are cleared and rebuilt, because those carry ids and
 * timestamps that would otherwise accumulate duplicates or go stale on every
 * run. A demo whose "3 bids" becomes "300 bids" after three seeds is not a demo.
 *
 * Nothing here reaches the network: lot photography points at SVGs in
 * /public/produce, generated by scripts/generate-placeholders.mjs.
 */
const prisma = new PrismaClient();

/**
 * Password for every seeded account.
 *
 * Seeded users need a real bcrypt hash or they cannot sign in — the credentials
 * provider checks `passwordHash` and refuses every user without one, so a
 * marketplace full of accounts you cannot log into is not a useful demo.
 * Development only; never reuse this in production.
 */
const SEED_PASSWORD = "kasethub123";

/** Stable prefixes so a re-seed can find and replace its own rows. */
const LOT_CODE_PREFIX = "KH-DEMO-";
const ORDER_CODE = "KH-ORD-DEMO-0001";
const SUPPLIER_ID = "seed-supplier-phothibfresh";

const PROVINCES: {
  nameTh: string;
  nameEn: string;
  code: string;
  region: Region;
  latitude: number;
  longitude: number;
}[] = [
  { nameTh: "เชียงใหม่", nameEn: "Chiang Mai", code: "CMI", region: "NORTH", latitude: 18.7883, longitude: 98.9853 },
  { nameTh: "ลำพูน", nameEn: "Lamphun", code: "LPN", region: "NORTH", latitude: 18.5745, longitude: 99.5122 },
  { nameTh: "เชียงราย", nameEn: "Chiang Rai", code: "CRI", region: "NORTH", latitude: 19.9104, longitude: 99.8265 },
  { nameTh: "ตาก", nameEn: "Tak", code: "TAK", region: "NORTH", latitude: 16.8864, longitude: 98.6283 },
  { nameTh: "อุดรธานี", nameEn: "Udon Thani", code: "UDT", region: "NORTHEAST", latitude: 17.4138, longitude: 102.7872 },
  { nameTh: "หนองคาย", nameEn: "Nong Khai", code: "NKI", region: "NORTHEAST", latitude: 17.8785, longitude: 102.4966 },
  { nameTh: "ศรีสะเกษ", nameEn: "Sisaket", code: "SKI", region: "NORTHEAST", latitude: 15.1203, longitude: 104.3256 },
  { nameTh: "นครปฐม", nameEn: "Nakhon Pathom", code: "NPM", region: "CENTRAL", latitude: 13.8198, longitude: 100.0371 },
  { nameTh: "สุพรรณบุรี", nameEn: "Suphan Buri", code: "SPB", region: "WEST", latitude: 14.4738, longitude: 100.0892 },
  { nameTh: "กำแพงเพชร", nameEn: "Kamphaeng Phet", code: "KPT", region: "CENTRAL", latitude: 14.6579, longitude: 99.5063 },
  { nameTh: "จันทบุรี", nameEn: "Chanthaburi", code: "CTI", region: "EAST", latitude: 13.3547, longitude: 100.9784 },
  { nameTh: "ระยอง", nameEn: "Rayong", code: "RYG", region: "EAST", latitude: 12.6808, longitude: 101.2773 },
  { nameTh: "ตราด", nameEn: "Trat", code: "TRT", region: "EAST", latitude: 12.2419, longitude: 102.9165 },
  { nameTh: "ชุมพร", nameEn: "Chumphon", code: "STP", region: "SOUTH", latitude: 10.4947, longitude: 99.3378 },
  { nameTh: "สุราษฎร์ธานี", nameEn: "Surat Thani", code: "STN", region: "SOUTH", latitude: 9.14, longitude: 99.33 },
  { nameTh: "นครศรีธรรมราช", nameEn: "Nakhon Si Thammarat", code: "NST", region: "SOUTH", latitude: 8.0863, longitude: 99.9637 },
];

/**
 * Demo accounts. Real Thai given names and surnames, real provinces, LINE ids
 * in the shape `line.me/ti/p/~{id}` expects (the id itself, no domain, no @).
 *
 * Farmers get a `shopName` so /shop/:id has something to render; the broker and
 * the buyer deliberately do not, since storefronts are a grower feature.
 */
const USERS: {
  email: string;
  nameTh: string;
  nameEn: string;
  role: "FARMER" | "BROKER" | "BUYER";
  verification: "BASIC" | "VERIFIED" | "CERTIFIED";
  province: string;
  /** Optional — an exporter's registered office may not name a district. */
  district?: string;
  phone: string;
  lineId?: string;
  whatsapp?: string;
  businessName?: string;
  shopName?: string;
  shopDescription?: string;
  ratingAvg: number;
  ratingCount: number;
  dealCount: number;
}[] = [
  {
    email: "somchai@kasethub.co",
    nameTh: "สมชาย ใจดีมาก",
    nameEn: "Somchai Jaideemaik",
    role: "FARMER",
    verification: "VERIFIED",
    province: "CMI",
    district: "สวนกุหลาบ",
    phone: "0812345671",
    lineId: "somchai.k",
    shopName: "สวนสมชายมะม่วง",
    shopDescription:
      "สวนมะม่วง 42 ไร่ อำเภอสวนกุหลาบ จังหวัดเชียงใหม่ ปลูกแบบอินทรีย์ไม้ผลพันธุ์มหาชนก น้ำดอกไม้ และเขียวเสวย คัดแยกตามขนาดตั้งแต่ในแปลง เก็บและบรรจุเอง ส่งได้ทั้งจังหวัด",
    ratingAvg: 4.9,
    ratingCount: 128,
    dealCount: 214,
  },
  {
    email: "malee@kasethub.co",
    nameTh: "มาลี ศรีสุข",
    nameEn: "Malee Srisuk",
    role: "FARMER",
    verification: "CERTIFIED",
    province: "CTI",
    district: "ท่าใหม่",
    phone: "0812345672",
    lineId: "malee.s",
    shopName: "แปลงทุเรียนมาลีท่าใหม่",
    shopDescription:
      "เกษตรกรทุเรียนพันธุ์กวางตากหมูและทอดมัน อำเภอท่าใหม่ จังหวัดจันทบุรี ดูแลแปลง 120 ไร่ มีห้องเย็นและห้องอบไอน้ำ เปิดขายมะม่วงน้ำปลาหวานและทุเรียนทอดตลอดฤดู",
    ratingAvg: 4.8,
    ratingCount: 96,
    dealCount: 187,
  },
  {
    email: "wichai@kasethub.co",
    nameTh: "วิชัย บุญมาก",
    nameEn: "Wichai Boonmak",
    role: "FARMER",
    verification: "VERIFIED",
    province: "LPN",
    district: "ป่าเปาะ",
    phone: "0812345675",
    lineId: "wichai.b",
    shopName: "ลำไยป่าเปาะวิชัย",
    shopDescription:
      "ลำไยพันธุ์อีดอและสัมพันธ์จากอำเภอป่าเปาะ จังหวัดลำพูน เน้นลำไยสดคัดพิเศษและลำไยแห้งแบบอบแดด ไม่ใช้สารกันธุรกันพืช",
    ratingAvg: 4.7,
    ratingCount: 74,
    dealCount: 131,
  },
  {
    email: "preecha@kasethub.co",
    nameTh: "ปรีชา วงศ์ทอง",
    nameEn: "Preecha Wongtong",
    role: "FARMER",
    verification: "BASIC",
    province: "STP",
    district: "ทุ่งสะเกียร์",
    phone: "0812345676",
    lineId: "preecha.w",
    shopName: "เงาะทุ่งสะเกียร์",
    shopDescription:
      "เงาะตงหวานและเงาะสดจากสวนในอำเภอทุ่งสะเกียร์ จังหวัดชุมพร คัดแยกเกรดตามขนาด เก็บปากกิ่งสดได้ทุกสัปดาห์",
    ratingAvg: 4.6,
    ratingCount: 52,
    dealCount: 88,
  },
  {
    email: "nok@kasethub.co",
    nameTh: "นก อินทร์แก้ว",
    nameEn: "Nok Inkaeo",
    role: "FARMER",
    verification: "VERIFIED",
    province: "CMI",
    district: "ดอยสุเทพ",
    phone: "0812345677",
    lineId: "nok.i",
    shopName: "สวนสมุนไพรดอยสุเทพ",
    shopDescription:
      "สมุนไพรสดและผลิตภัณฑ์จากธรรมชาติ เก็บจากป่าดอยสุเทพและแปลงชุมชน ส่งตรงถึงร้านอาหารและแม่ค้าในเชียงใหม่ทุกเช้า",
    ratingAvg: 4.9,
    ratingCount: 63,
    dealCount: 142,
  },
  {
    email: "broker@bangkokfresh.co",
    nameTh: "บริษัท โพธิ์เฟรช จำกัด",
    nameEn: "Borch Fresh Co., Ltd.",
    role: "BROKER",
    verification: "CERTIFIED",
    province: "CTI",
    district: "เมือง",
    phone: "0812345673",
    whatsapp: "66812345673",
    businessName: "โพธิ์เฟรช เอ็กซ์พอร์ต",
    ratingAvg: 4.7,
    ratingCount: 310,
    dealCount: 640,
  },
  {
    email: "buyer@globalfruit.io",
    nameTh: "บริษัท โกลบอลฟรุต เอ็กซ์พอร์ต",
    nameEn: "Global Fruit Export Co.",
    role: "BUYER",
    verification: "CERTIFIED",
    province: "CMI",
    phone: "0812345674",
    businessName: "โกลบอลฟรุต เอ็กซ์พอร์ต",
    ratingAvg: 4.9,
    ratingCount: 88,
    dealCount: 152,
  },
];

/** Map of role -> seeded account email, so lots and bids can reference them. */
const EMAIL = {
  farmerMango: "somchai@kasethub.co",
  farmerDurian: "malee@kasethub.co",
  farmerLongan: "wichai@kasethub.co",
  farmerTamarind: "preecha@kasethub.co",
  farmerHerbs: "nok@kasethub.co",
  broker: "broker@bangkokfresh.co",
  buyer: "buyer@globalfruit.io",
} as const;

type LotSeed = {
  code: string;
  titleTh: string;
  titleEn: string;
  variety: string;
  category: ProduceCategory;
  grade: Grade;
  ask: number;
  qty: number;
  minOrder: number;
  province: string;
  district: string;
  farmer: string;
  /** SVG slug under /public/produce — the first image becomes the cover. */
  image: string;
  description?: string;
  organic?: boolean;
  gap?: boolean;
  surplus?: boolean;
  coldChain?: ColdChainStatus;
  /**
   * Days until the lot spoils. The whole point of the marketplace is the race
   * against this number, so the seed deliberately spans critical (<1 day),
   * urgent (1-2 days) and comfortable windows.
   */
  expiresInDays: number;
  /** Hours until the auction closes. Only set on the lots under pressure. */
  auctionInHours?: number;
};

/**
 * Demo listings, grouped by the four categories in the brief.
 *
 * Prices are บาท/kg at a Thai wholesale-surplus level, and the mango varieties
 * are the ones actually grown in the provinces listed — Nam Dok Mai and Mahachanok
 * for Chiang Mai/Lamphun, Kaeo for Rayong, Ok Rong for Chanthaburi, Khiew Savee
 * for Chachoengsao-region supply.
 */
const LOTS: LotSeed[] = [
  // --- FRESH_FRUIT · ผลไม้สด -------------------------------------------
  {
    code: `${LOT_CODE_PREFIX}FF01`,
    titleTh: "มะม่วงน้ำดอกไม้ ต้นทุ่ง เกรดส่งออก",
    titleEn: "Export Grade Nam Dok Mai Mango",
    variety: "น้ำดอกไม้",
    category: "FRESH_FRUIT",
    grade: "A",
    ask: 78,
    qty: 12000,
    minOrder: 500,
    province: "CMI",
    district: "สวนกุหลาบ",
    farmer: EMAIL.farmerMango,
    image: "fresh-fruit",
    description:
      "มะม่วงน้ำดอกไม้จากแปลงท้องทุ่ง ปลูกอินทรีย์ ไม่ใช้สารกำจัดแมลง คัดขนาดตั้งแต่ 300 กรัมขึ้นไป สีเหลืองสม่ำเสมอทั้งล็อต เก็บสากให้สุกในแปลงก่อนส่งเข้าห้องเย็น 4 องศา",
    organic: true,
    expiresInDays: 9,
    auctionInHours: 62,
  },
  {
    code: `${LOT_CODE_PREFIX}FF02`,
    titleTh: "มะม่วงมหาชนก ผิวเขียว คัดพิเศษ",
    titleEn: "Premium Mahachanok Mango",
    variety: "มหาชนก",
    category: "FRESH_FRUIT",
    grade: "A",
    ask: 62,
    qty: 18000,
    minOrder: 800,
    province: "LPN",
    district: "ป่าเปาะ",
    farmer: EMAIL.farmerMango,
    image: "fresh-fruit",
    description:
      "มหาชนกเกรดคัด ผิวเขียวสด เนื้อแน่นไม่เสีย เหมาะทำน้ำแข็งใสและขนมไทย บรรจุตาขายพลาสติกใหม่ทุกใบ",
    expiresInDays: 7,
  },
  {
    code: `${LOT_CODE_PREFIX}FF03`,
    titleTh: "มะม่วงเขียวเสวย สุกพอดี รับประทานทันที",
    titleEn: "Tree-Ripened Khiew Savee Mango",
    variety: "เขียวเสวย",
    category: "FRESH_FRUIT",
    grade: "A",
    ask: 45,
    qty: 9000,
    minOrder: 400,
    province: "KPT",
    district: "คลองขุด",
    farmer: EMAIL.farmerMango,
    image: "fresh-fruit",
    description:
      "เขียวเสวยสุกสีเหลืองอมเขียว หวานกลิ่นหอม ไม่ใช้สารเร่งสุก พร้อมขายทันที ควรบริโภคภายใน 3 วัน",
    organic: true,
    expiresInDays: 1,
    auctionInHours: 18,
  },
  {
    code: `${LOT_CODE_PREFIX}FF04`,
    titleTh: "มะม่วงอกร่อง เนื้อหวาน ไม่เฝอ",
    titleEn: "Ok Rong Mango, Firm Flesh",
    variety: "อกร่อง",
    category: "FRESH_FRUIT",
    grade: "A",
    ask: 88,
    qty: 6000,
    minOrder: 300,
    province: "CTI",
    district: "ท่าใหม่",
    farmer: EMAIL.farmerDurian,
    image: "fresh-fruit",
    description:
      "อกร่องเนื้อแน่นสีส้มเข้ม เหมาะแกะเนื้อแช่แข็งและทำแป้งผลไม้ คัดจากสวนเกษตรกรที่ขึ้นกับดินดินเผาหิน ผลผลิตจำนวนจำกัด",
    expiresInDays: 12,
  },
  {
    code: `${LOT_CODE_PREFIX}FF05`,
    titleTh: "มะม่วงแก้ว สุกเต็มที่ ขนาดใหญ่",
    titleEn: "Fully Ripe Kaeo Mango, Large Size",
    variety: "แก้ว",
    category: "FRESH_FRUIT",
    grade: "B",
    ask: 34,
    qty: 7500,
    minOrder: 300,
    province: "SPB",
    district: "สระบุรี",
    farmer: EMAIL.farmerMango,
    image: "fresh-fruit",
    description:
      "มะม่วงแก้วสุกเต็มที หวานจัด เนื้อสีส้ม เหมาะแปรรูปเป็นน้ำมะม่วงหรือทำท้องไว้ กำหนดส่งภายใน 48 ชั่วโมง",
    expiresInDays: 2,
    auctionInHours: 26,
  },
  {
    code: `${LOT_CODE_PREFIX}FF06`,
    titleTh: "มังคะคัดเกรด ผิวมัน สวนระยอง",
    titleEn: "Premium Lang Durian Mangosteen",
    variety: "ลานเท",
    category: "FRESH_FRUIT",
    grade: "A",
    ask: 165,
    qty: 8000,
    minOrder: 300,
    province: "RYG",
    district: "บ้านโพธิ์",
    farmer: EMAIL.farmerDurian,
    image: "fresh-fruit-mangosteen",
    description:
      "มังคะลานเทจากสวนระยอง ผิวมันไม่แตก เนื้อเหนียวหวานอมเปรี้ยวเล็กน้อย เก็บเช้าส่งเย็น แพ็กแยกชั้นเพื่อกันการช้ำ",
    gap: true,
    expiresInDays: 5,
    auctionInHours: 30,
  },
  {
    code: `${LOT_CODE_PREFIX}FF07`,
    titleTh: "ลำไยอีดอ เกรด AA เนื้อทึบ",
    titleEn: "Export Grade Ae Dried Longan",
    variety: "อีดอ",
    category: "FRESH_FRUIT",
    grade: "A",
    ask: 74,
    qty: 9000,
    minOrder: 400,
    province: "LPN",
    district: "ป่าเปาะ",
    farmer: EMAIL.farmerLongan,
    image: "fresh-fruit-longan",
    description:
      "ลำไยอีดอเกรด AA เนื้อทึบ ตัดแต่งแล้วพร้อมขาย อบแห้งควบคุมความชื้น ไม่ใช้กำมะถังเพิ่มความหวาน",
    expiresInDays: 40,
  },
  {
    code: `${LOT_CODE_PREFIX}FF08`,
    titleTh: "ลำไยสดคัดพิเศษ ส่งร้านค้า",
    titleEn: "Premium Fresh Longan for Retail",
    variety: "สด",
    category: "FRESH_FRUIT",
    grade: "B",
    ask: 52,
    qty: 5200,
    minOrder: 200,
    province: "LPN",
    district: "บ้านธิ",
    farmer: EMAIL.farmerLongan,
    image: "fresh-fruit-longan",
    description:
      "ลำไยสดคัดขนาด 20-24 ลูกต่อกิโลกรัม เก็บเช้าส่งเย็นเข้าห้องแอร์คอนดิชั่นชั่น ควรจำหน่ายภายใน 4 วัน",
    expiresInDays: 3,
    auctionInHours: 40,
  },
  {
    code: `${LOT_CODE_PREFIX}FF09`,
    titleTh: "ทุเรียนกวางตากหมู เนื้อแน่น เบอร์ 3",
    titleEn: "Monthong Durian, Firm Flesh, No.3",
    variety: "กวางตากหมู",
    category: "FRESH_FRUIT",
    grade: "A",
    ask: 145,
    qty: 10000,
    minOrder: 500,
    province: "CTI",
    district: "ท่าใหม่",
    farmer: EMAIL.farmerDurian,
    image: "fresh-fruit-durian",
    description:
      "ทุเรียนกวางตากหมู เบอร์ 3 เนื้อแน่นไม่เละ หอม เก็บล้นกระดาษจากต้น ชั่งน้ำหนักจริงทุกใบ ส่งรถห้องเย็นภายในวันเก็บ",
    gap: true,
    expiresInDays: 4,
    auctionInHours: 20,
  },
  {
    code: `${LOT_CODE_PREFIX}FF10`,
    titleTh: "สับปะรดภูแล เนื้อสีเหลือง หวานกรอก",
    titleEn: "Gulf Pineapple, Golden Flesh",
    variety: "ภูแล",
    category: "FRESH_FRUIT",
    grade: "B",
    ask: 32,
    qty: 25000,
    minOrder: 1000,
    province: "TRT",
    district: "คลองตะปอ",
    farmer: EMAIL.farmerDurian,
    image: "fresh-fruit-pineapple",
    description:
      "สับปะรดภูแลตัดสดจากสวน เนื้อสีเหลืองอมทอง หวานกรอกไม่ใย ตัดตามออเดอร์ บรรจุกล่องโฟมที่มีช่องระบายอากาศ",
    expiresInDays: 11,
  },

  // --- NATURAL_PRODUCT · ผลิตภัณฑ์จากธรรมชาติ ---------------------------
  {
    code: `${LOT_CODE_PREFIX}NP01`,
    titleTh: "ผักกะเพราออร์แกนิก มัดละ 1 กก.",
    titleEn: "Organic Thai Basil, 1 kg Bunch",
    variety: "กะเพรา",
    category: "NATURAL_PRODUCT",
    grade: "A",
    ask: 96,
    qty: 2200,
    minOrder: 100,
    province: "CMI",
    district: "ดอยสุเทพ",
    farmer: EMAIL.farmerHerbs,
    image: "natural-product-herbs",
    description:
      "กะเพราออร์แกนิกปลูกแบบไม่ใช้สารเคมี มัดละ 1 กิโลกรัม ใบอ่อนสีเขียวสด กลิ่นหอมแรง เก็บเช้าก่อนแดดจัด",
    organic: true,
    expiresInDays: 1,
    auctionInHours: 10,
  },
  {
    code: `${LOT_CODE_PREFIX}NP02`,
    titleTh: "ใบมะยมและใบม้วนสด สายพันธุ์ภาคเหนือ",
    titleEn: "Fresh Antigonon and Erythrina Leaves",
    variety: "มะยม-ม้วน",
    category: "NATURAL_PRODUCT",
    grade: "A",
    ask: 68,
    qty: 1400,
    minOrder: 80,
    province: "CMI",
    district: "ดอยสุเทพ",
    farmer: EMAIL.farmerHerbs,
    image: "natural-product-herbs",
    description:
      "ใบมะยมและใบม้วนสดจากแปลงชุมชนดอยสุเทพ ใบใหญ่ ไม้แข็ง เหมาะทำแกงพื้นเมืองและขนมหัวผัก",
    organic: true,
    expiresInDays: 2,
  },
  {
    code: `${LOT_CODE_PREFIX}NP03`,
    titleTh: "ข้าวพันธุ์กว้าน ๑๕ กก./กระสอบ",
    titleEn: "Kwan 15 Paddy Rice, 15 kg Sack",
    variety: "กว้าน 15",
    category: "NATURAL_PRODUCT",
    grade: "A",
    ask: 24,
    qty: 30000,
    minOrder: 1500,
    province: "UDT",
    district: "กุมภวาปี",
    farmer: EMAIL.farmerHerbs,
    image: "natural-product",
    description:
      "ข้าวพันธุ์กว้าน 15 คัดสีขาวใส ความชื้น 14% สีเหลืองอ่อน เหมาะต้มห่อและทำข้าวต้ม บรรจุกระสอบป้ายคุณภาพชั้น 1",
    expiresInDays: 210,
  },
  {
    code: `${LOT_CODE_PREFIX}NP04`,
    titleTh: "มันฝรั่งหวาน เก็ดใหม่ ไม่ใช้สารกันชั้น",
    titleEn: "Freshly Dug Sweet Potato",
    variety: "หวาน",
    category: "NATURAL_PRODUCT",
    grade: "B",
    ask: 18,
    qty: 40000,
    minOrder: 2000,
    province: "SKI",
    district: "ขุมแผน",
    farmer: EMAIL.farmerHerbs,
    image: "natural-product",
    description:
      "มันฝรั่งหวานพันธุ์เหลือง เก็ดเพียงวานนี้ ไม่ใช้สารกันชั้น เนื้อแน่น นวลรส คัดขนาดเท่ากันทั้งกระสอบ",
    expiresInDays: 30,
  },
  {
    code: `${LOT_CODE_PREFIX}NP05`,
    titleTh: "กระเทียมแก้วสด ปลอกเดียว",
    titleEn: "Single-clove Fresh Garlic",
    variety: "แก้ว",
    category: "NATURAL_PRODUCT",
    grade: "A",
    ask: 92,
    qty: 6000,
    minOrder: 300,
    province: "KPT",
    district: "คลองขุด",
    farmer: EMAIL.farmerHerbs,
    image: "natural-product",
    description:
      "กระเทียมแก้วพันธุ์พื้นเมือง เก็ดกลิ่นแรง ใช้ทำยาฆ่าเชื้อและปรุงอาหาร คัดแล้วไม่มีก้นแตก",
    expiresInDays: 120,
  },

  // --- READY_TO_EAT · สินค้าพร้อมทาน ------------------------------------
  {
    code: `${LOT_CODE_PREFIX}RE01`,
    titleTh: "มะม่วงเขียวน้ำปลาหวาน ใส่น้ำปลาแล้ว",
    titleEn: "Ready-to-Eat Salted Fish Sauce Mango",
    variety: "เขียว",
    category: "READY_TO_EAT",
    grade: "A",
    ask: 120,
    qty: 5000,
    minOrder: 250,
    province: "CTI",
    district: "ท่าใหม่",
    farmer: EMAIL.farmerDurian,
    image: "ready-to-eat-mango",
    description:
      "มะม่วงเขียวสุกจากสวนท่าใหม่ ทำน้ำปลาหวานสูตรโบราณ หมักไว้ 5 เดือนจนตัดให้ถึงเปลือก บรรจุขวดแก้วสะอาด เปิดกินได้เลย เก็บได้นาน 6 เดือน",
    expiresInDays: 180,
  },
  {
    code: `${LOT_CODE_PREFIX}RE02`,
    titleTh: "ทุเรียนทอดมัน กวางตากหมู แช่แข็ง",
    titleEn: "Frozen Monthong Durian Chips",
    variety: "ทอดมัน",
    category: "READY_TO_EAT",
    grade: "A",
    ask: 220,
    qty: 4000,
    minOrder: 200,
    province: "CTI",
    district: "ท่าใหม่",
    farmer: EMAIL.farmerDurian,
    image: "ready-to-eat-durian",
    description:
      "ทุเรียนทอดมันจากเนื้อกวางตากหมู ไม่ใช้น้ำตาลเติม ทอดแบบกรอบนอกนุ่มใน แช่แข็ง -18°C ถึง -20°C บรรจุถุงซีล 500 กรัม อุ่นหรือทานเย็นได้ทันที",
    expiresInDays: 40,
  },
  {
    code: `${LOT_CODE_PREFIX}RE03`,
    titleTh: "น้ำมะพร้าวแกล้วสด ไม่เติมน้ำตาล",
    titleEn: "Fresh Young Coconut, No Added Sugar",
    variety: "แกล้ว",
    category: "READY_TO_EAT",
    grade: "A",
    ask: 28,
    qty: 12000,
    minOrder: 600,
    province: "NST",
    district: "สิงหนคร",
    farmer: EMAIL.farmerTamarind,
    image: "ready-to-eat",
    description:
      "มะพร้าวแกล้วอายุไม่เกิน 40 วัน เนื้อน้ำหวานธรรมชาติ เจาะพร้อมดื่ม ไม่ใส่สารกันเสีย เก็บที่อุณหภูมิห้องเย็นส่งวันเดียว",
    expiresInDays: 6,
  },
  {
    code: `${LOT_CODE_PREFIX}RE04`,
    titleTh: "เงาะสดคัดพิเศษ กรอก ไม่เฝอ",
    titleEn: "Premium Crisp Fresh Tamarind",
    variety: "สด",
    category: "READY_TO_EAT",
    grade: "A",
    ask: 58,
    qty: 7400,
    minOrder: 300,
    province: "STP",
    district: "ทุ่งสะเกียร์",
    farmer: EMAIL.farmerTamarind,
    image: "ready-to-eat",
    description:
      "เงาะสดเก็ดจากสวนทุ่งสะเกียร์ ฝักใหญ่ เมล็ดน้อย เนื้อกรอกหวานอมเปรี้ยว ทานเล่นหรือทำน้ำเงาะได้ทันที เก็บเย็น",
    expiresInDays: 8,
  },
  {
    code: `${LOT_CODE_PREFIX}RE05`,
    titleTh: "ขนมเผื่อกรอบ ทอดสด สูตรไม่ใส่ขาว",
    titleEn: "Fresh Fried Phuek Muean Crackers",
    variety: "เผื่อก",
    category: "READY_TO_EAT",
    grade: "B",
    ask: 85,
    qty: 1600,
    minOrder: 100,
    province: "CRI",
    district: "แม่จันทร์",
    farmer: EMAIL.farmerHerbs,
    image: "ready-to-eat",
    description:
      "ขนมเผื่อกรอบทอดสดจากแปลงเชียงราย ใช้ข้าวเหนียวเชียงรายล้วน ไม่ใส่ขาวผสม บรรจุถุงสูญญากาศพร้อมขาย หมดอายุ 10 วัน",
    organic: true,
    expiresInDays: 10,
  },

  // --- DRIED_FOOD · อาหารแห้ง --------------------------------------------
  {
    code: `${LOT_CODE_PREFIX}DF01`,
    titleTh: "กล้วยแผ่นทอดกรอบ รสธรรมชาติ",
    titleEn: "Crispy Fried Banana Chips",
    variety: "กล้วยน้ำวา",
    category: "DRIED_FOOD",
    grade: "A",
    ask: 95,
    qty: 3500,
    minOrder: 150,
    province: "KPT",
    district: "คลองขุด",
    farmer: EMAIL.farmerHerbs,
    image: "dried-food-banana-chip",
    description:
      "กล้วยแผ่นทอดจากกล้วยน้ำวาสดของสวน ทอดกรอบนอกนุ่มใน ไม่ใส่สี ไม่ใช้น้ำตาลเติม บรรจุถุงสุญญากาศพร้อมจำหน่าย เก็บได้ 6 เดือน",
    organic: true,
    expiresInDays: 180,
  },
  {
    code: `${LOT_CODE_PREFIX}DF02`,
    titleTh: "มะม่วงแห้งสีเหลือง เนื้อเหนียว ไม่เติมสาร",
    titleEn: "Yellow Dried Mango, No Preservatives",
    variety: "มะม่วงแห้ง",
    category: "DRIED_FOOD",
    grade: "A",
    ask: 145,
    qty: 2800,
    minOrder: 120,
    province: "CTI",
    district: "ท่าใหม่",
    farmer: EMAIL.farmerDurian,
    image: "dried-food-dried-mango",
    description:
      "มะม่วงแห้งอบแดดจากมะม่วงเขียวเสวยสายพันธุ์ท่าใหม่ สีเหลืองส้มสม่ำเสมอ เนื้อเหนียวไม่เฉียว ไม่ใช้สารกันเสียหรือสีผสม บรรจูถุงแถวซีล",
    expiresInDays: 240,
  },
  {
    code: `${LOT_CODE_PREFIX}DF03`,
    titleTh: "ลำไยแห้งอบแดด เกรดส่งออก",
    titleEn: "Sun-dried Export Grade Longan",
    variety: "ลำไยแห้ง",
    category: "DRIED_FOOD",
    grade: "A",
    ask: 168,
    qty: 2000,
    minOrder: 100,
    province: "LPN",
    district: "ป่าเปาะ",
    farmer: EMAIL.farmerLongan,
    image: "dried-food-longan",
    description:
      "ลำไยแห้งพันธุ์อีดอ อบแดดโดยไม่ใช้เครื่องอบฟัง เนื้อทึบ สีน้ำตาลอ่อน หอมหวาน คัดเกรดเก็บใบใหญ่ เก็บในถุงสุญญากาศ",
    gap: true,
    expiresInDays: 300,
  },
  {
    code: `${LOT_CODE_PREFIX}DF04`,
    titleTh: "กล้วยตากแห้งสลาย หวานกลิ่นธรรมชาติ",
    titleEn: "Dried Banana Chips, Natural Ripeness",
    variety: "กล้วยตาก",
    category: "DRIED_FOOD",
    grade: "B",
    ask: 78,
    qty: 5000,
    minOrder: 250,
    province: "SPB",
    district: "สระบุรี",
    farmer: EMAIL.farmerMango,
    image: "dried-food",
    description:
      "กล้วยตากแห้งสลายจากกล้วยสุกในแปลง ไม่ใช้สารฟอกสี มีสีข้าวซอยดูข้าง หอมหวาน บรรจุในถุงอลามิเนตพร้อมขาย",
    expiresInDays: 150,
  },
];

/**
 * Market price index rows for the ticker.
 *
 * Keyed on a stable id so re-seeding replaces them rather than appending. The
 * ticker takes the most recent row per (category, variety), so one row per
 * entry is enough.
 */
const MARKET_PRICES: {
  id: string;
  category: ProduceCategory;
  variety: string;
  province?: string;
  pricePerKg: number;
  changePct: number;
  sparkline: number[];
}[] = [
  { id: "mp-mango-namdokmai", category: "FRESH_FRUIT", variety: "มะม่วง น้ำดอกไม้", province: "CMI", pricePerKg: 78, changePct: 4.2, sparkline: [70, 72, 71, 75, 74, 77, 78] },
  { id: "mp-mango-khiewsavee", category: "FRESH_FRUIT", variety: "มะม่วง เขียวเสวย", province: "KPT", pricePerKg: 45, changePct: -2.8, sparkline: [50, 49, 47, 48, 46, 45, 45] },
  { id: "mp-mangosteen", category: "FRESH_FRUIT", variety: "มังคะ", province: "RYG", pricePerKg: 165, changePct: 6.1, sparkline: [148, 152, 149, 156, 158, 162, 165] },
  { id: "mp-longan-fresh", category: "FRESH_FRUIT", variety: "ลำไยสด", province: "LPN", pricePerKg: 52, changePct: 1.4, sparkline: [55, 54, 53, 54, 52, 53, 52] },
  { id: "mp-herbs-basil", category: "NATURAL_PRODUCT", variety: "ผักกะเพรา", province: "CMI", pricePerKg: 96, changePct: 3.1, sparkline: [88, 90, 89, 92, 94, 95, 96] },
  { id: "mp-rice-kwan15", category: "NATURAL_PRODUCT", variety: "ข้าว กว้าน 15", pricePerKg: 24, changePct: 0.6, sparkline: [24, 24, 23.5, 24, 24.2, 23.8, 24] },
  { id: "mp-salted-mango", category: "READY_TO_EAT", variety: "มะม่วงน้ำปลาหวาน", pricePerKg: 120, changePct: -1.1, sparkline: [124, 123, 122, 121, 122, 120, 120] },
  { id: "mp-durian-chips", category: "READY_TO_EAT", variety: "ทุเรียนทอด", pricePerKg: 220, changePct: 2.3, sparkline: [212, 214, 216, 215, 218, 219, 220] },
  { id: "mp-banana-chip", category: "DRIED_FOOD", variety: "กล้วยแผ่นทอด", pricePerKg: 95, changePct: -0.4, sparkline: [96, 95, 96, 95, 94, 95, 95] },
  { id: "mp-dried-mango", category: "DRIED_FOOD", variety: "มะม่วงแห้ง", pricePerKg: 145, changePct: 5.7, sparkline: [132, 134, 138, 136, 140, 143, 145] },
];

/**
 * Demo broker watches for /alerts.
 *
 * A broker follows fresh fruit generally, plus two narrowed watches. Between
 * them they should match several of the demo lots, so the alert list is not
 * empty on a fresh seed — an empty alerts page is indistinguishable from a
 * broken one.
 */
const WATCHES: {
  owner: string;
  category: ProduceCategory;
  province?: string;
  label?: string;
  minQuantityKg?: number;
}[] = [
  { owner: EMAIL.broker, category: "FRESH_FRUIT", label: "ผลไม้สดทุกชนิดที่ใกล้หมดอายุ" },
  { owner: EMAIL.broker, category: "FRESH_FRUIT", province: "CTI", label: "ผลไม้สดจันทบุรี" },
  { owner: EMAIL.broker, category: "FRESH_FRUIT", province: "CMI", minQuantityKg: 2000, label: "เชียงใหม่ ขั้นต่ำ 2 ตัน" },
  { owner: EMAIL.broker, category: "READY_TO_EAT", label: "สินค้าพร้อมทาน" },
  { owner: EMAIL.buyer, category: "DRIED_FOOD", label: "อาหารแห้งส่งออก" },
  { owner: EMAIL.buyer, category: "FRESH_FRUIT", province: "LPN", label: "ลำไยลำพูน" },
];

/** Local placeholder for a lot's cover photo. */
function coverUrl(slug: string): string {
  return `/produce/${slug}.svg`;
}

async function main() {
  console.log("Seeding provinces…");
  const provinceByCode = new Map<string, string>();
  for (const p of PROVINCES) {
    const row = await prisma.province.upsert({
      where: { code: p.code },
      update: p,
      create: p,
    });
    provinceByCode.set(p.code, row.id);
  }

  console.log("Seeding users…");
  // bcrypt is deliberately slow, so the hash is computed once and shared: all
  // demo accounts use the same password, and hashing it seven times would add
  // seconds to every seed run for no benefit.
  const passwordHash = await hashPassword(SEED_PASSWORD);
  const userByEmail = new Map<string, string>();
  /** Broker's trading name, captured for the Supplier row created below. */
  const businessNameByEmail = new Map<string, string>();
  for (const u of USERS) {
    // `businessName` has no column on User. It is the name a broker trades
    // under, and the register route stores it on the separate Supplier record
    // (see app/api/auth/register), so it must be pulled out of the user row
    // rather than spread into it. Spreading it blindly is a runtime
    // PrismaClientValidationError, not a compile error, because `rest` is typed
    // as the seed's own object shape.
    const { province, businessName, ...rest } = u;
    if (businessName) businessNameByEmail.set(u.email, businessName);
    const provinceId = provinceByCode.get(province) ?? null;
    const row = await prisma.user.upsert({
      where: { email: u.email },
      update: { ...rest, passwordHash, provinceId },
      create: { ...rest, passwordHash, provinceId },
    });
    userByEmail.set(u.email, row.id);
  }

  const id = (email: string): string => {
    const found = userByEmail.get(email);
    if (!found) throw new Error(`Seed user missing: ${email}`);
    return found;
  };

  const broker = id(EMAIL.broker);
  const buyer = id(EMAIL.buyer);
  const farmerA = id(EMAIL.farmerMango);

  console.log("Seeding supplier…");
  await prisma.supplier.upsert({
    where: { id: SUPPLIER_ID },
    // Updated as well as created: the name now comes from the broker's
    // businessName, so editing it in USERS has to take effect on a re-run.
    update: {
      ownerId: broker,
      nameTh: businessNameByEmail.get(EMAIL.broker) ?? "โพธิ์เฟรช เอ็กซ์พอร์ต",
      provinceId: provinceByCode.get("CTI") ?? null,
      district: "เมือง",
    },
    create: {
      id: SUPPLIER_ID,
      ownerId: broker,
      nameTh: businessNameByEmail.get(EMAIL.broker) ?? "โพธิ์เฟรช เอ็กซ์พอร์ต",
      nameEn: "Borch Fresh Export",
      tier: "CERTIFIED",
      provinceId: provinceByCode.get("CTI") ?? null,
      district: "เมือง",
      escrowCap: 5_000_000,
    },
  });

  /**
   * Clear the previous run's marketplace before rebuilding.
   *
   * Cascade takes the dependent bids, orders, images, price logs and chat with
   * it, so this one delete is enough to make the whole volatile section
   * reproducible. Ordered first, because everything below creates rows that
   * point at these lots.
   *
   * Scoped to the demo lot-code prefix: this never touches a lot a developer
   * created by hand through the UI, which is the one thing you would be upset
   * to lose by running a seed.
   */
  console.log("Clearing previous demo lots…");
  await prisma.lot.deleteMany({
    where: { lotCode: { startsWith: LOT_CODE_PREFIX } },
  });
  await prisma.marketPrice.deleteMany({});
  await prisma.brokerWatch.deleteMany({
    where: { user: { email: { in: [EMAIL.broker, EMAIL.buyer] } } },
  });

  console.log(`Seeding ${LOTS.length} lots…`);
  const now = Date.now();
  const day = 86_400_000;
  const hour = 3_600_000;

  for (const l of LOTS) {
    const data = {
      lotCode: l.code,
      titleTh: l.titleTh,
      titleEn: l.titleEn,
      variety: l.variety,
      category: l.category,
      grade: l.grade,
      askPricePerKg: l.ask,
      quantityKg: l.qty,
      availableQtyKg: l.qty,
      minOrderKg: l.minOrder,
      isSurplus: l.surplus ?? false,
      organic: l.organic ?? false,
      gapCertified: l.gap ?? false,
      // Fresh fruit needs a cold chain; dried goods and shelf-stable products
      // do not, and claiming otherwise makes the filter meaningless.
      coldChain: l.coldChain ?? (l.category === "FRESH_FRUIT" ? "CHILLED" : "AMBIENT"),
      description: l.description,
      provinceId: provinceByCode.get(l.province) ?? null,
      district: l.district,
      farmerId: id(l.farmer),
      harvestDate: new Date(now - 2 * day),
      expiresAt: new Date(now + l.expiresInDays * day),
      auctionEndsAt: l.auctionInHours ? new Date(now + l.auctionInHours * hour) : null,
      status: "ACTIVE" as const,
    } satisfies Prisma.LotUncheckedCreateInput;

    await prisma.lot.create({
      data: {
        ...data,
        // The first image is the cover — lot cards and the market grid all
        // read images[0], so ordering starts at zero and increments.
        images: {
          create: [
            {
              url: coverUrl(l.image),
              altTh: `${l.titleTh} — ภาพตัวอย่าง`,
              sortOrder: 0,
            },
          ],
        },
        // A short ask history so the price-trend strip on the lot page has
        // something to draw, tracing a gentle decline to the current ask.
        priceLogs: {
          create: [
            { pricePerKg: Number((l.ask * 1.12).toFixed(2)), source: "ASK", createdAt: new Date(now - 6 * day) },
            { pricePerKg: Number((l.ask * 1.06).toFixed(2)), source: "ASK", createdAt: new Date(now - 4 * day) },
            { pricePerKg: Number((l.ask * 1.02).toFixed(2)), source: "ASK", createdAt: new Date(now - 2 * day) },
            { pricePerKg: l.ask, source: "ASK", createdAt: new Date(now - day) },
          ],
        },
      },
    });
  }

  console.log("Seeding bids…");
  const lots = await prisma.lot.findMany({
    where: { lotCode: { startsWith: LOT_CODE_PREFIX } },
    select: { id: true, lotCode: true, askPricePerKg: true, minOrderKg: true, expiresAt: true },
    orderBy: { lotCode: "asc" },
  });

  /**
   * Bids on the lots that are close to spoiling.
   *
   * Placing these only on at-risk lots is deliberate: those are the lots a
   * broker would actually be watching, so the demo's bid board, dashboards and
   * deal room are all populated around the same story.
   */
  const atRisk = lots
    .filter((lot) => lot.expiresAt && lot.expiresAt.getTime() - now < 2 * day)
    .slice(0, 6);

  for (let i = 0; i < atRisk.length; i++) {
    const lot = atRisk[i];
    // Bid at or just above the ask — a bid below the ask is a rejection.
    const price = Number((lot.askPricePerKg + (i % 2 === 0 ? 1.5 : 0.5)).toFixed(2));
    await prisma.bid.create({
      data: {
        lotId: lot.id,
        bidderId: i % 2 === 0 ? buyer : broker,
        pricePerKg: price,
        quantityKg: lot.minOrderKg * (1 + (i % 2)),
        status: "PENDING",
        note:
          i % 2 === 0
            ? "พร้อมรับที่โรงงานภายในวันนี้ ขอปิดดีลครับ"
            : "ขอใบเซอร์ GAP และผลตรวจสารตกค้างพร้อมกันครับ",
        expiresAt: new Date(now + 36 * hour),
      },
    });
  }

  console.log("Seeding a settled order…");
  const firstLot = lots.find((l) => l.lotCode === `${LOT_CODE_PREFIX}FF01`) ?? lots[0];
  if (firstLot) {
    const qty = firstLot.minOrderKg * 2;
    const subtotal = Math.round(firstLot.askPricePerKg * qty);
    const fee = Math.round(subtotal * 0.03);

    const order = await prisma.order.create({
      data: {
        orderCode: ORDER_CODE,
        lotId: firstLot.id,
        buyerId: buyer,
        sellerId: farmerA,
        quantityKg: qty,
        pricePerKg: firstLot.askPricePerKg,
        subtotalThb: subtotal,
        platformFee: fee,
        netPayoutThb: subtotal - fee,
        status: "COMPLETED",
        createdAt: new Date(now - 9 * day),
        closedAt: new Date(now - 6 * day),
        events: {
          create: [
            { status: "ESCROW_DEPOSITED", note: "วางเงินประกัน", actorId: buyer, createdAt: new Date(now - 9 * day) },
            { status: "QUALITY_INSPECTED", note: "ตรวจสอบสินค้าและตรวจสารตกค้าผ่าน", actorId: buyer, createdAt: new Date(now - 8 * day) },
            { status: "LOADED_SHIPPED", note: "ขึ้นรถห้องเย็น ออกจากสวนแล้ว", actorId: farmerA, createdAt: new Date(now - 7 * day) },
            { status: "COMPLETED", note: "ผู้ซื้อตรวจรับสินค้าแล้ว ปล่อยเงินโอน", actorId: buyer, createdAt: new Date(now - 6 * day) },
          ],
        },
      },
    });

    // Threads are one row per message, and the order was just created, so there
    // is nothing stale to clear here.
    console.log("Seeding a completed negotiation…");
    await prisma.chatMessage.createMany({
      data: [
        {
          orderId: order.id,
          senderId: buyer,
          body: "สนใจล็อตนี้ครับ ขอทราบสภาพการบรรจุและอุณหภูมิขนส่งหน่อยครับ",
          kind: "TEXT",
          createdAt: new Date(now - 9 * day),
          readAt: new Date(now - 9 * day + hour),
        },
        {
          orderId: order.id,
          senderId: farmerA,
          body: "บรรจุตาขาย ห้องเย็น 4 องศา ตั้งแต่คัดแยกจากแปลงครับ ส่งได้พรุ่งนี้เช้า",
          kind: "TEXT",
          createdAt: new Date(now - 9 * day + hour),
          readAt: new Date(now - 9 * day + 2 * hour),
        },
        {
          orderId: order.id,
          senderId: buyer,
          body: "รับเงื่อนไขครับ ขอปิดดีลที่ราคานี้",
          kind: "OFFER",
          offerPricePerKg: firstLot.askPricePerKg,
          offerQuantityKg: qty,
          createdAt: new Date(now - 8 * day),
          readAt: new Date(now - 8 * day + hour),
        },
        {
          orderId: order.id,
          senderId: farmerA,
          body: "รับข้อเสนอแล้วครับ วางเงินประกันได้เลย ผมจะเตรียมเอกสาร GAP ให้พร้อมรถ",
          kind: "TEXT",
          createdAt: new Date(now - 8 * day + 2 * hour),
          readAt: new Date(now - 8 * day + 3 * hour),
        },
        {
          orderId: order.id,
          senderId: buyer,
          body: "ชำระเงินแล้วครับ รอตรวจสอบคุณภาพที่โรงงาน",
          kind: "TEXT",
          createdAt: new Date(now - 7 * day),
          readAt: new Date(now - 7 * day + hour),
        },
        {
          orderId: order.id,
          senderId: farmerA,
          body: "ผลตรวจสารตกค้าอยู่ในระบบแล้วครับ ผลการตรวจเป็นไปตามมาตรฐาน ส่งรายงานให้ในห้องนี้",
          kind: "TEXT",
          createdAt: new Date(now - 7 * day + 2 * hour),
          readAt: new Date(now - 7 * day + 3 * hour),
        },
      ],
    });

    // An unfinished thread, so /deals/:id opens on a live negotiation rather
    // than a settled order.
    console.log("Seeding a live negotiation…");
    const openLot = lots.find((l) => l.lotCode === `${LOT_CODE_PREFIX}FF06`) ?? lots[1];
    if (openLot) {
      const openBid = await prisma.bid.findFirst({
        where: { lotId: openLot.id, status: "PENDING" },
        select: { id: true },
      });
      if (openBid) {
        await prisma.chatMessage.createMany({
          data: [
            {
              bidId: openBid.id,
              senderId: broker,
              body: "สวัสดีครับ สนใจมังคะล็อตนี้ แต่ขอปรับเป็นสองเท่าของขั้นต่ำ แลกกับราคาที่ลดลงเล็กน้อยครับ",
              kind: "TEXT",
              createdAt: new Date(now - 3 * hour),
              readAt: new Date(now - 2 * hour),
            },
            {
              bidId: openBid.id,
              senderId: broker,
              body: "ปรับปริมาณและราคาตามที่คุยกันครับ",
              kind: "OFFER",
              offerPricePerKg: Number((openLot.askPricePerKg - 3).toFixed(2)),
              offerQuantityKg: openLot.minOrderKg * 2,
              createdAt: new Date(now - 2 * hour),
            },
          ],
        });
      }
    }
  }

  console.log("Seeding market prices…");
  await prisma.marketPrice.createMany({
    data: MARKET_PRICES.map((m) => ({
      id: m.id,
      category: m.category,
      variety: m.variety,
      provinceId: m.province ? (provinceByCode.get(m.province) ?? null) : null,
      pricePerKg: m.pricePerKg,
      changePct: m.changePct,
      sparkline: m.sparkline,
    })),
  });

  console.log("Seeding broker watches…");
  for (const w of WATCHES) {
    await prisma.brokerWatch.create({
      data: {
        userId: id(w.owner),
        category: w.category,
        provinceId: w.province ? (provinceByCode.get(w.province) ?? null) : null,
        label: w.label,
        minQuantityKg: w.minQuantityKg ?? null,
      },
    });
  }

  const [
    provinceCount,
    userCount,
    lotCount,
    bidCount,
    priceCount,
    messageCount,
    watchCount,
  ] = await Promise.all([
    prisma.province.count(),
    prisma.user.count(),
    prisma.lot.count(),
    prisma.bid.count(),
    prisma.marketPrice.count(),
    prisma.chatMessage.count(),
    prisma.brokerWatch.count(),
  ]);

  console.log(
    `\nSeed complete: ${provinceCount} provinces, ${userCount} users, ${lotCount} lots, ${bidCount} bids, ${priceCount} market prices, ${messageCount} chat messages, ${watchCount} watches.`,
  );
  console.log(`\nSign in with any address below and the password: ${SEED_PASSWORD}`);
  for (const u of USERS) {
    console.log(`  ${u.role.padEnd(6)} ${u.email.padEnd(26)} ${u.nameTh}`);
  }
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
